# Generated by Django 5.1.4 on 2025-07-29 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_App', '0002_shopsettings_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='name',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='phone',
            field=models.CharField(default=55, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='shop_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(choices=[('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato')], default='Poppins', max_length=100)),
                ('layout_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('boxed', 'Boxed')], default='light', max_length=20)),
                ('sidebar_style', models.CharField(choices=[('default', 'Default'), ('mini', 'Mini Sidebar'), ('floating', 'Floating')], default='default', max_length=20)),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('flat', 'Flat'), ('outline', 'Outline')], default='rounded', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
