# Generated by Django 5.1.4 on 2025-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_App', '0006_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
