# Generated by Django 5.2.4 on 2025-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_App', '0012_tailoringorder_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
