# Generated by Django 5.2.4 on 2025-08-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B_App', '0013_tbl_product_gst_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='contact',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B_App.customer'),
        ),
    ]
